services:
  db:
    image: mysql:8.0
    container_name: projectbar_db
    restart: always
    environment:
      MYSQL_DATABASE: bar_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectbar_backend
    restart: always
    ports:
      - "8090:8090"
    environment:
      - DB_URL=jdbc:mysql://db:3306/bar_db?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

volumes:
  mysql_data:
