server:
  port: 8090

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/bar_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}

logging:
  level:
    root: INFO
    com.app.projectbar: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
